name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4
    - name: Install msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
    - name: Install dependencies
      run: |
        set -x
        pacman -S --needed --noconfirm pactoys
        pacboy -S --needed --noconfirm openssl:p meson:p clang:p 
    - name: Configure
      run: |
        set -x
        cd Crypto
        CC=clang CXX=clang++ meson setup build
    - name: Build
      run: |
        cd Crypto/build
        ninja
    - name: Upload windows
      uses: actions/upload-artifact@v4.3.0
      with: 
        name: libcrypto-win-x64
        path: Crypto/build/libcrypto.dll
